# Custom image?

#image: ocaml/opam:alpine-ocaml-4.12-fp does not work...
image:
    file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' && eval $(opam env) # runs during prebuild    
    before: echo 'before' && opam install --deps-only --with-test .  && make build
    command: echo 'start script'
    
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview


